name: Simulate External Checks

on:
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  statuses: write
  contents: read

jobs:
  create-fake-external-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Currents Status Check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Creating fake Currents status..."

          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
            -d '{
              "state": "failure",
              "target_url": "https://currents.dev/fake-report-123",
              "description": "Currents E2E Tests Failure",
              "context": "Currents"
            }'

      - name: Simulate Argos Check Run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Creating fake Argos check-run..."

          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/check-runs \
            -d '{
              "name": "Argos Visual Regression",
              "head_sha": "${{ github.event.pull_request.head.sha }}",
              "status": "completed",
              "conclusion": "failure",
              "details_url": "https://argos-ci.com/fake-build-456",
              "external_id": "argos-5678"
            }'
