on:
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  statuses: write
  contents: read

jobs:
  create-fake-external-checks:
    runs-on: ubuntu-latest
    steps:
      # - name: Create Fake Currents Status (Mocked)
      #   run: |
      #     curl -X POST \
      #       -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #       -H "Accept: application/vnd.github.v3+json" \
      #       https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
      #       -d '{
      #         "state": "failure",
      #         "target_url": "https://currents.dev/fake-report-123",
      #         "description": "1 failed 200 skipped",
      #         "context": "Currents E2E Tests"
      #       }'

      # - name: Create Fake Argos Status (Mocked)
      #   run: |
      #     curl -X POST \
      #       -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #       -H "Accept: application/vnd.github.v3+json" \
      #       https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
      #       -d '{
      #         "state": "failure",
      #         "target_url": "https://currents.dev/fake-report-123",
      #         "description": "1 failed",
      #         "context": "argos"
      #       }'

      - name: Simulate check run
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/check-runs \
            -d '{
              "name": "Node.js test",
              "status": "completed",
              "conclusion": "failure",
              "url": "https://nodjs.failure001",
              "external_id": "nodejs"
              "context": "nodjs"
            }'

          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/check-runs \
            -d '{
              "name": "Node.js test",
              "status": "completed",
              "conclusion": "failure",
              "url": "https://nodjs.failure002",
              "external_id": "nodejs"
              "context": "nodjs"
            }'